"""
Pydantic schemas package.

This module exports all Pydantic schemas for request/response validation.
"""

from app.schemas.approval_request import (
    ApprovalDecision,
    ApprovalRequestCreate,
    ApprovalRequestResponse,
)
from app.schemas.audit_log import (
    AuditLogResponse,
    AuditLogsListResponse,
)
from app.schemas.auth import (
    APIResponse,
    ErrorDetail,
    ErrorResponse,
    LoginRequest,
    LoginResponse,
    LogoutResponse,
    MeResponse,
    PasswordResetConfirm,
    PasswordResetRequest,
    PasswordResetResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    RegisterResponse,
    TokenResponse,
    UserCreate,
    UserMeResponse,
    UserResponse,
)
from app.schemas.chat import (
    Attachment,
    AttachmentUpload,
    ChatHistoryData,
    ChatHistoryResponse,
    ChatMessageCreate,
    ChatMessageDataResponse,
    ChatMessageResponse,
    ChatMessageWithUser,
    ChatResponseMetadata,
    ChatSendDataResponse,
    ChatSendResponse,
    ChatStreamRequest,
    ProjectChatContext,
    StreamChunk,
)
from app.schemas.knowledge import (
    DocumentDeleteResponse,
    DocumentDeleteResult,
    DocumentIngestResponse,
    DocumentIngestResult,
    FullIngestionResponse,
    FullIngestionResult,
    KnowledgeDocumentIngest,
    KnowledgeIngestRequest,
    KnowledgeIngestResponse,
    KnowledgeIngestResult,
    KnowledgeSearchData,
    KnowledgeSearchRequest,
    KnowledgeSearchResponse,
    KnowledgeSearchResult,
    KnowledgeStats,
    KnowledgeStatsResponse,
    SourceTypeStats,
)
from app.schemas.project_share import (
    ProjectShareCreate,
    ProjectShareResponse,
    ProjectShareUpdate,
)
from app.schemas.project import (
    PaginationMeta,
    ProjectCreate,
    ProjectDataResponse,
    ProjectDeleteResponse,
    ProjectDetailDataResponse,
    ProjectDetailResponse,
    ProjectListData,
    ProjectListResponse,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.quote import (
    QuoteCreate,
    QuoteDataResponse,
    QuoteDeleteResponse,
    QuoteDetailDataResponse,
    QuoteDetailResponse,
    QuoteGenerateDataResponse,
    QuoteGenerateRequest,
    QuoteGenerationMetadata,
    QuoteGenerationResponse,
    QuoteListData,
    QuoteListResponse,
    QuoteRegenerateRequest,
    QuoteResponse,
    QuoteStatusUpdate,
    QuoteSummaryResponse,
    QuoteUpdate,
)

__all__ = [
    # Approval request schemas
    "ApprovalDecision",
    "ApprovalRequestCreate",
    "ApprovalRequestResponse",
    # Audit log schemas
    "AuditLogResponse",
    "AuditLogsListResponse",
    # Auth schemas
    "APIResponse",
    "ErrorDetail",
    "ErrorResponse",
    "LoginRequest",
    "LoginResponse",
    "LogoutResponse",
    "MeResponse",
    "PasswordResetConfirm",
    "PasswordResetRequest",
    "PasswordResetResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RegisterResponse",
    "TokenResponse",
    "UserCreate",
    "UserMeResponse",
    "UserResponse",
    # Project schemas
    "PaginationMeta",
    "ProjectCreate",
    "ProjectDataResponse",
    "ProjectDeleteResponse",
    "ProjectDetailDataResponse",
    "ProjectDetailResponse",
    "ProjectListData",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectUpdate",
    # Project share schemas
    "ProjectShareCreate",
    "ProjectShareResponse",
    "ProjectShareUpdate",
    # Quote schemas
    "QuoteCreate",
    "QuoteDataResponse",
    "QuoteDeleteResponse",
    "QuoteDetailDataResponse",
    "QuoteDetailResponse",
    "QuoteGenerateDataResponse",
    "QuoteGenerateRequest",
    "QuoteGenerationMetadata",
    "QuoteGenerationResponse",
    "QuoteListData",
    "QuoteListResponse",
    "QuoteRegenerateRequest",
    "QuoteResponse",
    "QuoteStatusUpdate",
    "QuoteSummaryResponse",
    "QuoteUpdate",
    # Chat schemas
    "Attachment",
    "AttachmentUpload",
    "ChatHistoryData",
    "ChatHistoryResponse",
    "ChatMessageCreate",
    "ChatMessageDataResponse",
    "ChatMessageResponse",
    "ChatMessageWithUser",
    "ChatResponseMetadata",
    "ChatSendDataResponse",
    "ChatSendResponse",
    "ChatStreamRequest",
    "ProjectChatContext",
    "StreamChunk",
    # Knowledge schemas
    "DocumentDeleteResponse",
    "DocumentDeleteResult",
    "DocumentIngestResponse",
    "DocumentIngestResult",
    "FullIngestionResponse",
    "FullIngestionResult",
    "KnowledgeDocumentIngest",
    "KnowledgeIngestRequest",
    "KnowledgeIngestResponse",
    "KnowledgeIngestResult",
    "KnowledgeSearchData",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "KnowledgeSearchResult",
    "KnowledgeStats",
    "KnowledgeStatsResponse",
    "SourceTypeStats",
]
